### ISSUE TITLE
Open/Close session?

### ISSUE THREAD

**Issue by Harm10** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#25]
wc3270 lets me save sessions with specific names. Currently there is no keyword Open session and Close session. Can this be added?

**Comment by samuelpcabral** [comment]
Sessions are shortcuts used by the wc3270 application to open an already configured connection.

I don't think this is the purpose of the library, since you can easily manage your connection settings in Robot Framework variables which can be passed to the keyword "open connection"

the only relevant configuration that cannot be passed today would be the model number, which is fixed as 24 rows x 80 columns.

but I think this could be changed in the future. If you have access to a mainframe other than 24x80.

**Comment by Harm10** [comment]
I agree although this blocks reusing pre-set sessions. Will you record other screen dimensions than 23x80 somewhere on an enhancement list?

**Comment by samuelpcabral** [comment]
Sure, bt only when i have access to a mainframe with different dimensions than 23x80 .. i will create a new issue to keep this.
