### ISSUE TITLE
Setup the model number

### ISSUE THREAD

**Issue by samuelpcabral** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#31]
Today the library open the x3270 app with model number 2 as default. (24 rows x 80 columns).
Implement the choice of this model in the keyword "Open connection" as a new argument, but to do this, we need access to a mainframe with this different configuration than we have at pub400.com. In order to perform all tests.

**Comment by Harm10** [comment]
I can help! But you probably already figured that out?

**Comment by samuelpcabral** [comment]
I still need access to a mainframe with a different model than pub400 to make this change. Or you can make the modification and send a merge request. after all it is open source.

**Comment by Harm10** [comment]
I am willing to test different models if you tell me what to test exactly.
But PUB400 can also be accessed with different models. Use configuration wizard of WC3270 to create such sessions so you can compare?

**Comment by centhil** [comment]
@samuelpcabral I can also help testing with different models. My Case I need to use 
Model Number 2
Oversize  24x87
Font Size 24

Can you pls help

**Comment by samuelpcabral** [comment]
@centhil all of the size references is hard coded inside x3270.py, for example the "def _check_limits" or "def _read_all_screen" you need to research how is the best way to setup the sizes before doing the open connection, (maybe a new argument in the import) and passa this parameters to all of the functions that need the size... I can´t help because I don´t have a different model size to test.

**Comment by Harm10** [comment]
Just to let you know that you can test perfectly with the model number on PUB400.
If you create session files with wc3270 specifying the different model numbers and connect with PUB400 you get different sized screens.
I have not tried this from RF but it is possible to check out directly on PUB400.

**Comment by Harm10** [comment]
I did some testing and you can specify the model number in RF just fine. 
If you specify `-xrm	wc3270.model: 5` you get a shifted display were lines seem not properly to be aligned.
If I compare the window with sessions specifying the different models and using those models through RF my conclusion is that the problem lies in the window opened to show the screen.
A session with the different models opens a window that is different in dimensions while this package opens a windows each time with the same dimensions leading to weird displays if you choose a different model than 2.
I haven't been able yet to find where these dimensions are set. Maybe someone knows?

@robinmatz It would help if the package is extended by a new command "Open connection from session file". You were planning something for this new command?

**Comment by robinmatz** [comment]
The difficult thing is not specifying a different model, you could do that, as Harm said, by
``Open Connection    host     extra_args=['-xrm', 'wc3270.model: 4']``
for example.

But as Samuel pointed out, there are several functions in the x3270 class that use the screen dimensions. Therefore, it needs to be indicated at some place what model is being used so the library can react accordingly.

The interesting question would be where. As an import parameter? Or as an additional argument to Open Connection? Or maybe both, so that the import parameter is chosen as a default for a new connection, but can be overwritten?

**Comment by robinmatz** [comment]
I played around a bit with the ideas of setting the model as an import parameter. We might additionally create a new keyword `Set Model` to allow changing the model at runtime, too.

For those interested, you can see the experimental changes in the [setup-model-numbers](https://github.com/robinmatz/Robot-Framework-Mainframe-3270-Library/tree/setup-model-numbers) on my fork.

However, I wasn't able to test any different models successfully, because running wc3270 with `-xrm wc3270.model:4` still gave me the same dimensions.

**Comment by samuelpcabral** [comment]
Published in version 4.0
