### ISSUE TITLE
Set custom character-set

### ISSUE THREAD

**Issue by amir-gauss** [Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library#64]
Is there any way to add custom codepage of character set during initial wc3270?

**Comment by robinmatz** [comment]
Hi @amir-gauss ,

since version 3.0 there is the possibility to set ``extra_args`` to the ``Open Connection`` keyword.

As said in the [documentation](https://raw.githack.com/Altran-PT-GDC/Robot-Framework-Mainframe-3270-Library/master/doc/Mainframe3270.html#Open%20Connection), ``extra_args`` can be

> a list, or a path to a file, containing [x3270 command line options](https://x3270.miraheze.org/wiki/Category:Command-line_options).

Say you wanted your codepage to be french, you would open a new connection like so:

```robot
*** Settings ***
Library    Mainframe3270


*** Test Cases ***
Test With Codepage French
    @{extra_args}=    Create List    -codepage    french
    Open Connection    myhost.com    extra_args=${extra_args}
```

**Comment by robinmatz** [comment]
Hi @amir-gauss , did the above approach work for you?

**Comment by robinmatz** [comment]
Assuming that the issue was resolved, I am going to close this now.
